sudo: required

language: java

jdk:
    - oraclejdk7

addons:
    apt:
        packages:
            - ant
            - rcs

#ant test is the default target, but I want to make it explicit
script:
    - ant test
