sudo: false

language: java

jdk:
    - oraclejdk7

addons:
    apt:
        packages:
            - ant
            - git

#ant test is the default target, but I want to make it explicit
script:
    - ant test
